name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint_and_typecheck:
    name: lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install uv and dependencies
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - run: uv sync
      - name: lint
        run: uv run ruff check .
      - name: typecheck
        run: uv run mypy snap_http/

  unit_test:
    name: tox unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install uv and dependencies
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - run: uv sync
      - name: install additional python versions
        run: uv python install 3.8 3.9 3.10 3.11 3.12 3.13 3.14
      - name: tox unit test
        run: uv run tox

  integration_test:
    uses: ./.github/workflows/integration-test.yml
